---
  # onReady
  consoleMessage: "The bot is ready!"
  loggedInAs: "Logged in as"
  # Application Data
  token: "your bots token here"
  client_id: "your bots application id here"
  guild_id: "your bots development server id here"