# -------------------------
# Version
# -------------------------
RedesignedInformationBot_Version: "1.5"
# -------------------------
# General Configuration
# -------------------------

bot_name: "Redesigned Information Bot"
token: "your bots token here"
client_id: "your bots application id here"
guild_id: "your bots development server id here"

# -------------------------
# Commands
# -------------------------

consoleCommandError: "There was an error while executing this command!"
helpDescription: "Help command that shows list of commands"
userDescription: "Sends information about yourself"
serverDescription: "Sends information about this guild"
cantExecuteCommand: "There was an error while executing this command!"

# -------------------------
# onReady
# -------------------------

consoleMessage: "The bot is ready!"
loggedInAs: "Logged in as"

# -------------------------
# Other
# -------------------------

space: " "

# -------------------------